/* - A Random Quote Generator - */

// Study guide for this project - https://drive.google.com/file/d/1s5grutGuQFwJcQP8bFwEI69Q8FCkGdDk/view?usp=sharing
/*** EXTRA WHAT I WANT TO DO IT!!!
.random gradadien on every quote.
.User can create his own quote, with will show up: Quote, Name, Citation(website),Date, all will be adder to the Array!
**/


/*** 
  Create the array of quote objects and name it `quotes`.
  Add at least five quote objects to the `quotes` array.
  Give each quote object a `quote` and `source` property.
  Add the `citation` property to at least one object in the array.
  Add the `year` property to at least one object in the array.
  Use console.log() to log your array of quotes to the console.
***/

  let quotes = [ 
  {
    quote:'Talk is cheap. Show me the code.',
    source: 'Linus Torvalds',
    citation: 'Twitter',
    year: 2001
},
{
  quote:'Programs must be written for people to read, and only incidentally for machines to execute.',
  source: 'Harold Abelson',
  citation:'Structure and Interpretation of Computer Programs',
  year: 1984
},
{
  quote:'Success is not final, failure is not fatal: it is the courage to continue that counts.',
  source: 'Winston S. Churchill',
  citation:'Inspiration Magazine',
  year:''
},
{ 
  quote:"If at first you don't succeed, try, try again. Then quit. No use being a damn fool about it.",
  source: 'W.C. Fields', 
  citation:'',
  year:''
},
{
  quote:'Try not to become a man of success. Rather become a man of value.',
  source: 'Albert Einstein', 
  citation:'University Newspaper',
  year:1972},
{
  quote:'Success is getting what you want, happiness is wanting what you get',
  source: 'W. P. Kinsella',
  citation:'',
  year:1976
}
  
  ];

//console.log(quotes);


/***
  The `getRandomQuote` function is create
  to search for a nem/random Quote insite of the variable [quote] array.
 */ 
 function getRandomQuote(quotes)
{
  return quotes[Math.floor(Math.random()*quotes.length)];
};


/*  This function changes the background color of the page.
every times that a page reloads or a new quote is generated.
*/

function rand_bg_color() {
    let x = Math.floor(Math.random() * 256);
    let y = Math.floor(Math.random() * 256);
    let z = Math.floor(Math.random() * 256);
    let bgColor = "rgb(" + x + "," + y + "," + z + ")";
  
    document.body.style.background = bgColor;
    }

rand_bg_color();


function getRandomQuote() {
    let random_nub = Math.floor(Math.random() * (quotes.length));
    return quotes[random_nub];
}

/* - This function will execute the change of the background with the fucntion (rand_bg_color),
    and will get the Quotes generated by the fucntion (getRandomQuote) and print them all with 
    the classes associated to each one.
- */

function printQuote(){

  rand_bg_color();

  let callQuote = getRandomQuote(quotes);
  let x = callQuote;
  let quote = "<p class='quote'>"+ x.quote +"</p>";
  quote +=  "<p class='source'>"+ x.source +"</p>";
  if(x.citation !== ''){
    quote += "<span class='source'>"+ x.citation +"</span>";
  }
  if(x.year !== '')  {
    quote += "<span class='source'>"+ x.year +"</sapn>";
  }

  document.getElementById('quote-box').innerHTML = quote;

  }


/* - Timer -*/
function timer(){

let i = 0;

function increment() {
  i++;
  printQuote()
}

setInterval(increment, 8000);

}


/***
  When the "Show another quote" button is clicked, the event listener 
  below will be triggered, and it will call, or "invoke", the `printQuote` 
  function. So do not make any changes to the line of code below this 
  comment.
***/
document.getElementById('loadQuote').addEventListener("click", function () {

    printQuote();
   
  }, false);
printQuote();
timer();

// Remember to delete the comments that came with this file, and replace them with your own code comments.